# Site settings
# in the templates available like {{ site.myvariable }}.
title: Experienced Software Developer based in New York City.
email: willburghard@gmail.com
brand: Will Burghard
headline: Software Developer and Musician
description: > # this means to ignore newlines until "baseurl:"
  Experienced software developer based in New York City.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://willburghard.github.io/" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: willburghard@gmail.com
phone: +1-347-924-3146

# Tracking
googleAnalitycsID: UA-83933844-1

